version: "3.7"
services:
  # Api Service
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      CORS_ALLOWED_ORIGINS: "http://localhost:8000,http://localhost:5672"
      API_PORT: "8081"
      MYSQL_USER: gomail
      MYSQL_PASSWORD: gomail
      MYSQL_DATABASE: image_gomail
      DB_HOST: tcp(db:3306)
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_ERLANG_COOKIE: rabbitmq_cookie
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_PORT: 5672
    ports:
      - "8081"
    volumes:
      - ./:/go:rw
    networks:
      - backend

networks:
  backend:
    driver: "bridge"
    external: 
      name: gomail-network
